# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"  # 使用最新的 Python 3.x 版本
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade 
        pip install hpf
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test
      run: |
        python -m hpf
